import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // New sidebar for the Robotics Course structure
  roboticsCourseSidebar: [
    {
      type: 'category',
      label: '00 - Introduction',
      items: [
        { type: 'doc', id: 'intro/index', label: '00.1 - Introduction to Robotics' },
        { type: 'doc', id: 'intro/spacekit-example', label: '00.2 - SpaceKit Example' },
      ],
    },
    {
      type: 'category',
      label: "01 - Module 1: ROS 2 — Robotic Nervous System",
      items: [
        { type: 'doc', id: 'module-1/ros2-overview', label: '01.1 - ROS 2 Overview' },
        { type: 'doc', id: 'module-1/ros2-nodes', label: '01.2 - ROS 2 Nodes' },
        { type: 'doc', id: 'module-1/ros2-topics-services', label: '01.3 - Topics, Services, and Actions' },
        { type: 'doc', id: 'module-1/urdf-humanoids', label: '01.4 - URDF for Humanoids' },
      ],
    },
    {
      type: 'category',
      label: "02 - Module 2: Digital Twin (Gazebo & Unity)",
      items: [
        { type: 'doc', id: 'module-2/gazebo-physics', label: '02.1 - Gazebo Physics Simulation' },
        { type: 'doc', id: 'module-2/unity-rendering', label: '02.2 - Unity Digital Twin' },
        { type: 'doc', id: 'module-2/sensors', label: '02.3 - Sensor Simulation' },
      ],
    },
    {
      type: 'category',
      label: "03 - Module 3: NVIDIA Isaac — Robot Brain",
      items: [
        { type: 'doc', id: 'module-3/isaac-sim', label: '03.1 - NVIDIA Isaac Sim' },
        { type: 'doc', id: 'module-3/isaac-ros', label: '03.2 - Isaac ROS' },
        { type: 'doc', id: 'module-3/nav2', label: '03.3 - Nav2 Path Planning' },
      ],
    },
    {
      type: 'category',
      label: "04 - Module 4: Vision-Language-Action",
      items: [
        { type: 'doc', id: 'module-4/whisper', label: '04.1 - Whisper Voice Commands' },
        { type: 'doc', id: 'module-4/llm-planning', label: '04.2 - LLM Cognitive Planning' },
        { type: 'doc', id: 'module-4/vla-architecture', label: '04.3 - Vision-Language-Action (VLA)' },
      ],
    },
    {
      type: 'category',
      label: "05 - Hardware & Deployment",
      items: [
        { type: 'doc', id: 'hardware/overview', label: '05.1 - Hardware Integration Overview' },
        { type: 'doc', id: 'hardware/workstation', label: '05.2 - Workstation Specifications' },
        { type: 'doc', id: 'hardware/jetson', label: '05.3 - Jetson Deployment' },
        { type: 'doc', id: 'hardware/robot-platforms', label: '05.4 - Robot Platforms' },
        { type: 'doc', id: 'hardware/lab-setup', label: '05.5 - Lab Setup Guidelines' },
      ],
    },
    {
      type: 'category',
      label: "06 - Capstone Project",
      items: [
        { type: 'doc', id: 'capstone/overview', label: '06.1 - Capstone Project Overview' },
        { type: 'doc', id: 'capstone/architecture', label: '06.2 - Capstone Project Architecture' },
        { type: 'doc', id: 'capstone/evaluation', label: '06.3 - Capstone Project Evaluation' },
        { type: 'doc', id: 'capstone/deployment-notes', label: '06.4 - From Sim-to-Real Deployment' },
        { type: 'doc', id: 'capstone/capstone-lab', label: '06.5 - Capstone Project Lab' },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
